# Generated by Django 5.2.8 on 2025-11-22 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('drawn', 'Drawn'), ('emails_sent', 'Emails Sent'), ('emails_error', 'Emails Error')], default='draft', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_dependent', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, help_text='Optional note for the organizer or Santa')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='secretsanta.game')),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='secretsanta.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='secretsanta.player')),
            ],
        ),
        migrations.CreateModel(
            name='DependentProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='secretsanta.game')),
                ('dependent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_assignment', to='secretsanta.player')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_for', to='secretsanta.player')),
            ],
        ),
        migrations.CreateModel(
            name='ForbiddenPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forbidden_pairs', to='secretsanta.game')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forbidden_as_giver', to='secretsanta.player')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forbidden_as_receiver', to='secretsanta.player')),
            ],
            options={
                'unique_together': {('giver', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='secretsanta.game')),
                ('giver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_as_giver', to='secretsanta.player')),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_as_receiver', to='secretsanta.player')),
            ],
            options={
                'unique_together': {('game', 'giver')},
            },
        ),
    ]
