# Generated by Django 5.2.8 on 2025-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forbiddenpair',
            name='is_reciprocal',
            field=models.BooleanField(default=False, help_text='Si es recíproca, también se prohíbe que receiver regale a giver'),
        ),
    ]
